-- Room Inventory Data for All Properties
-- This script creates individual physical rooms for each room type
-- Each room type gets 2-4 individual physical rooms
-- Using direct room ID lookups to avoid subquery issues
INSERT INTO public.room_inventory (room_id, room_number, is_available, created_at, updated_at) VALUES
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Riverside Hut 1' AND p.title = 'The Turtle Huts' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Riverside Hut 1' AND p.title = 'The Turtle Huts' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Riverside Hut 2' AND p.title = 'The Turtle Huts' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Riverside Hut 2' AND p.title = 'The Turtle Huts' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 1' AND p.title = 'The Turtle Huts' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 1' AND p.title = 'The Turtle Huts' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 1' AND p.title = 'The Turtle Huts' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 2' AND p.title = 'The Turtle Huts' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 2' AND p.title = 'The Turtle Huts' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Riverside Hut 2' AND p.title = 'The Turtle Huts' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mountain View 1' AND p.title = 'Keekoo Stays' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mountain View 1' AND p.title = 'Keekoo Stays' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mountain View 2' AND p.title = 'Keekoo Stays' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mountain View 2' AND p.title = 'Keekoo Stays' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 1' AND p.title = 'Keekoo Stays' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 1' AND p.title = 'Keekoo Stays' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 1' AND p.title = 'Keekoo Stays' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 2' AND p.title = 'Keekoo Stays' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 2' AND p.title = 'Keekoo Stays' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Mountain View 2' AND p.title = 'Keekoo Stays' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Mountain View' AND p.title = 'Keekoo Stays' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Mountain View' AND p.title = 'Keekoo Stays' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Royal Room 1' AND p.title = 'Sundays Forever Kings Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Royal Room 1' AND p.title = 'Sundays Forever Kings Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Royal Room 2' AND p.title = 'Sundays Forever Kings Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Royal Room 2' AND p.title = 'Sundays Forever Kings Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 1' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 2' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 3' AND p.title = 'Annfield Cottage' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room 3' AND p.title = 'Annfield Cottage' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 1' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 2' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 3' AND p.title = 'Jharipani Castle' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Castle Room 3' AND p.title = 'Jharipani Castle' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 1' AND p.title = 'The Lanswood Estate' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 1' AND p.title = 'The Lanswood Estate' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 2' AND p.title = 'The Lanswood Estate' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 2' AND p.title = 'The Lanswood Estate' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 3' AND p.title = 'The Lanswood Estate' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Forest Room 3' AND p.title = 'The Lanswood Estate' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 1' AND p.title = 'Karinya Villas' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 1' AND p.title = 'Karinya Villas' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 2' AND p.title = 'Karinya Villas' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 2' AND p.title = 'Karinya Villas' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 3' AND p.title = 'Karinya Villas' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lake View Villa 3' AND p.title = 'Karinya Villas' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Glamp Tent 1' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Glamp Tent 2' AND p.title = 'Castle Glamp' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Orchard Room 1' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Orchard Room 1' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Orchard Room 2' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Orchard Room 2' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 1' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 1' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 1' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 2' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 2' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Orchard Room 2' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Orchard Room' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Orchard Room' AND p.title = 'Moustache Select Mukteshwar' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Stone Room 1' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Stone Room 1' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Stone Room 2' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Stone Room 2' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 1' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 1' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 1' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 2' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 2' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Stone Room 2' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Stone Room' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Stone Room' AND p.title = 'Kasauli Pebbles' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Family Room 1' AND p.title = 'LivingStone Ojuven Resort' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Family Room 1' AND p.title = 'LivingStone Ojuven Resort' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Family Room 2' AND p.title = 'LivingStone Ojuven Resort' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Family Room 2' AND p.title = 'LivingStone Ojuven Resort' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mud House 1' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mud House 1' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mud House 2' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Mud House 2' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 1' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Glamp Tent 2' AND p.title = 'Monkey Mud House and Glamps' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Alpine Room 1' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Alpine Room 1' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Alpine Room 2' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Alpine Room 2' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 1' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 1' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 1' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 2' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 2' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Alpine Room 2' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Alpine Room' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Alpine Room' AND p.title = 'Mountain Bliss Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 1' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 1' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 2' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 2' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 3' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Victorian Room 3' AND p.title = 'Iris Cottage Dalhousie' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 1' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 1' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 2' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 2' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 3' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Castle Room 3' AND p.title = 'Naddi Castle Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 1' AND p.title = 'Winterfell The Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 1' AND p.title = 'Winterfell The Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 2' AND p.title = 'Winterfell The Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 2' AND p.title = 'Winterfell The Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 3' AND p.title = 'Winterfell The Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Nordic Room 3' AND p.title = 'Winterfell The Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 1' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 1' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 2' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 2' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 3' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Kashmiri Room 3' AND p.title = 'Zabarwan Peaks Villa' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lakefront Tent 1' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lakefront Tent 1' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lakefront Tent 2' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Lakefront Tent 2' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 1' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 1' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 1' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 2' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 2' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Lakefront Tent 2' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Lakefront Tent' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Lakefront Tent' AND p.title = 'Desert Blue Pangong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Jungle Room 1' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Jungle Room 1' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Jungle Room 2' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Jungle Room 2' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 1' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 1' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 1' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 2' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 2' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Jungle Room 2' AND p.title = 'The Alpine Jungle Stay' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 1' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 1' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 2' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 2' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 3' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Eco Villa 3' AND p.title = 'The Firefly Eco Luxury Retreat' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 1' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 1' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 2' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Heritage Room 2' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 1' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Super Deluxe Heritage Room 2' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'C', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Family Suite Heritage Room' AND p.title = 'Bellevue Homestay Shillong' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 1' AND p.title = 'Adlai Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 1' AND p.title = 'Adlai Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 2' AND p.title = 'Adlai Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 2' AND p.title = 'Adlai Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 3' AND p.title = 'Adlai Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Tribal Room 3' AND p.title = 'Adlai Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 1' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 1' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 2' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 2' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'B', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 3' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'A', true, NOW(), NOW()),
((SELECT r.id FROM public.rooms r JOIN public.properties p ON r.property_id = p.id WHERE r.name = 'Deluxe Hillside Room 3' AND p.title = 'Mishmi Takin Homestay' LIMIT 1), 'B', true, NOW(), NOW());

